#! /bin/bash

sxhkd &
$HOME/.config/polybar/launch.sh

#Desktops
bspc monitor -d 1 2 3 4 5 6

#Config
bspc config border_width         3
bspc config window_gap          15

bspc config split_ratio          0.50
bspc config borderless_monocle   true 
bspc config gapless_monocle      true 
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config click_to_focus	 true

#Rules
bspc rule -a Gimp desktop=^6 state=floating follow=no
bspc rule -a Steam desktop=^5 state=floating follow=no
